name: Simple CI Pipeline

# Phiên bản đơn giản của CI/CD - chỉ check cơ bản nhất
# Để sử dụng: đổi tên file này thành ci.yml và xóa file ci.yml hiện tại

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job đơn nhất: Kiểm tra cả frontend và backend
  basic-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Frontend checks
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci
      
    - name: Frontend syntax check (ESLint)
      working-directory: frontend
      run: npm run lint
      
    - name: Frontend build test
      working-directory: frontend
      run: npm run build
      
    # Backend checks  
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        
    - name: Backend syntax check
      working-directory: backend
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Test imports
      working-directory: backend
      run: |
        python -c "import app; print('✅ Backend imports OK')"
        
    - name: Success notification
      run: |
        echo " Basic CI checks passed!"
        echo " Frontend build successful"
        echo " Backend syntax OK" 
